Implement Direct Message Chat
MahemaS27/covey.town pull request #19
Opened 2021-03-30 02:41 UTC by MahemaS27

- Added logic in `recieveMessage` method in controller to handle a `DirectMessage` case
- Added helper method to find correct listener to send message to
- Updated commenting for methods in `CoveyTownController`
- Added tests for new functionality

2021-03-30 21:12 UTC, abigailhodge commented
Please add a test for the new Socket logic in `CoveyTownsSocket.test.ts`

2021-04-01 16:24 UTC, abigailhodge requested changes

2021-04-01 16:24 UTC, abigailhodge commented on services/roomService/src/client/CoveyTownsSocket.test.ts
> +    const [receivedMessage] = await Promise.all([messageReceived]);
I think you should make sure that it goes to both players: i.e. when you're making joinData2, i.e. create two socket clients based on the two `apiClient.joinTown` data, set up `messageReceived` Promises for both of them, and make sure they both resolve/that the received messages both match `message`

2021-04-01 16:24 UTC, abigailhodge commented on services/roomService/src/client/TestUtils.ts
> +      location: player1.location,
Is this necessary with the `createDirectMessageForTesting` test?

2021-04-01 16:24 UTC, abigailhodge commented on services/roomService/src/lib/CoveyTownController.test.ts
> +      expect(directMockListeners[0].onMessageReceived).toBeCalledWith(message);
Again, I think you should create a listener for player1 and make sure that they're also receiving their own message

2021-04-01 16:24 UTC, abigailhodge commented on services/roomService/src/lib/CoveyTownController.ts
> +    return directMessageListener[0];
Wait, shouldn't you be returning all of them? The way the frontend is set up, every player (including the one who sent the message) involved in a MessageChain needs to get the message.

2021-04-01 17:11 UTC, MahemaS27 commented on services/roomService/src/client/CoveyTownsSocket.test.ts
> +      coveyTownID: town.coveyTownID,
i dont know why this looks like i have a bunch of spaces between these lines when i open it in vscode its doesnt look like that

2021-04-01 17:52 UTC, michelle-pine approved these changes
LGTM!

2021-04-01 17:52 UTC, michelle-pine commented on services/roomService/src/lib/CoveyTownController.ts
> +   * Informs the correct listener that a direct message has been sent
i dont think this comment is fully accurate to what the function does. it just retrieves the listeners, it doesn't inform them

2021-04-01 21:52 UTC, abigailhodge approved these changes
LGTM, thanks for the changes!

2021-04-02 14:35 UTC, merged