Anika/message chain
MahemaS27/covey.town pull request #5
Opened 2021-03-20 01:00 UTC by anikarabenhorst

Implements MessageChain class and tests.
- includes functions to update isActive and addMessage()
- addMessage only checks whether the chain isActive before adding- the Player would handle deciding which chain to call addMessage on. If we think it's necessary I can go back and add checks for correct directMessageID, but we won't be able to check whether proximity vs global is right chain
- one Q: why were we needing participants list again? i included it from the design but I was unsure

2021-03-20 17:51 UTC, MahemaS27 reviewed
Participants would be needed to know which players are listening for chat events

2021-03-20 21:20 UTC, michelle-pine approved these changes
LGTM!

2021-03-20 21:20 UTC, michelle-pine commented on services/roomService/src/types/MessageChain.ts
> +     * @param newMessage The new message to add to this chain
thanks for commenting!

2021-03-20 21:20 UTC, michelle-pine commented on services/roomService/src/types/MessageChain.test.ts
> +function createMessageForTesting(type: MessageType, player1: Player, player2id?: string) {
good naming

2021-03-20 21:27 UTC, abigailhodge requested changes

2021-03-20 21:27 UTC, abigailhodge commented on services/roomService/src/types/MessageChain.ts
> +        this._isActive = value;
You should probably use a standard TS setter for this 

```
set isActive(value: boolean) {
        this._isActive= value;
    }
```
Then when calling it on a `message` you just need to do `message.isActive = value`

2021-03-21 00:26 UTC, anikarabenhorst commented
> Participants would be needed to know which players are listening for chat events

2021-03-21 00:30 UTC, anikarabenhorst commented
> Participants would be needed to know which players are listening for chat events

Okay- but that just applies for the direct message right? So its a duplicate of information in the directMessageID

2021-03-21 00:39 UTC, abigailhodge approved these changes
LGTM!

2021-03-21 00:40 UTC, merged